### ISSUE TITLE
Add ability to promote properties on per message base

### ISSUE THREAD

**Issue by svetvasilev** [svetvasilev/transmock#11]
Currently it is only possible to promote a limited set of adapter properties on a per receive location base. There will be much greater benefits if it is possible to do this on a per message base. This way one can create much more fine grained tests

**Comment by refurbs** [comment]
Hi Svet,

Is this likely to include a wider set of properties?  Perhaps non-fixed?  I ask because I would ideally like to mock a SharePoint adapter.  The SharePoint adapter is able to pass in and promote properties into BizTalk.  I'm particularly interested in WSS.inPropertiesXml.  [https://docs.microsoft.com/en-us/biztalk/core/windows-sharepoint-services-adapter-properties-reference](url).
Something to perhaps consider when designing and developing this.

Rob

**Comment by svetvasilev** [comment]
Hi Rob, strangely enough i havent received any sort of notification about your comment. Apols for not replying earlier. Have you tried this feature with the WSS properties already? Check the Wiki for detailed description of the syntax and supported out-of box properties. In case you miss smthg ping me here.
